import type { Config } from 'tailwindcss';

const config = {
  content: [],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        'background-elevated': 'var(--color-background-elevated)',
        'background-subtle': 'var(--color-background-subtle)',
        foreground: 'var(--color-foreground)',
        'foreground-muted': 'var(--color-foreground-muted)',
        'foreground-subtle': 'var(--color-foreground-subtle)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'surface-control': 'var(--color-surface-control)',
        'surface-control-disabled': 'var(--color-surface-control-disabled)',
        'surface-hover': 'var(--color-surface-hover)',
        'surface-active': 'var(--color-surface-active)',
        'overlay-backdrop': 'var(--color-overlay-backdrop)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-muted': 'var(--color-accent-muted)',
        'accent-foreground': 'var(--color-accent-foreground)',
        destructive: 'var(--color-destructive)',
        ring: 'var(--color-ring)',
        info: 'var(--color-info)',
        'info-foreground': 'var(--color-info-foreground)',
        'info-muted': 'var(--color-info-muted)',
        'info-border': 'var(--color-info-border)',
        success: 'var(--color-success)',
        'success-foreground': 'var(--color-success-foreground)',
        'success-muted': 'var(--color-success-muted)',
        'success-border': 'var(--color-success-border)',
        warning: 'var(--color-warning)',
        'warning-foreground': 'var(--color-warning-foreground)',
        'warning-muted': 'var(--color-warning-muted)',
        'warning-border': 'var(--color-warning-border)',
        error: 'var(--color-error)',
        'error-foreground': 'var(--color-error-foreground)',
        'error-muted': 'var(--color-error-muted)',
        'error-border': 'var(--color-error-border)',
        neutral: 'var(--color-neutral)',
        'neutral-foreground': 'var(--color-neutral-foreground)',
        'neutral-muted': 'var(--color-neutral-muted)',
        'neutral-border': 'var(--color-neutral-border)',
      },
      boxShadow: {
        'highlight-inset': 'inset 0 1px 0 var(--color-highlight-inset)',
        popover: 'var(--shadow-popover)',
        dialog: 'var(--shadow-dialog)',
        toast: 'var(--shadow-toast)',
        card: 'var(--shadow-card)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        serif: 'var(--font-serif)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
    },
  },
} satisfies Config;

export default config;
